spring.application.name=IT Service Management System

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/itsm_db
spring.data.mongodb.database=itsm_db

# Server Port
server.port=8081

# JWT Configuration
jwt.secret=itsm-secret-key-2026-itp-nu-06-sliit-university-northern-campus-very-long-secret
jwt.expiration=86400000

# Email Configuration (Optional - configure your SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tharaniyajeyapalan29@gmail.com
spring.mail.password=jiccpisaxouixpdr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.com.itsm=DEBUG

# CORS
app.cors.allowedOrigins=http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# application.properties
cloudinary.cloud-name=dint66fwl
cloudinary.api-key=515942956414282
cloudinary.api-secret=I9igmGz-ISkAvhrdgEPmG3d2z0A